### ISSUE TITLE
Complete In-kind proposal workplan

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/Galaxy-Clustering#7]
Use the form at 
https://ls.st/ikc-wp

**Comment by tms-epcc** [comment]
10/JUL/23
- waiting for confirmation from KnutO and AprajitaV before starting this

**Comment by tms-epcc** [comment]
04/SEP/23
- form can be filled in but NOT submitted.
- need to first get the ok from Rubin IPC team to hit the submit button

**Comment by damonge** [comment]
Saved first attempt at completing the form (not submitted)

**Comment by tms-epcc** [comment]
01/DEC/23
- KnutO said to go ahead and submit
- David and Boris informed

**Comment by tms-epcc** [comment]
20/DEC/23
- @damonge submitted the form on 04/DEC/23 and forwarded the resutling email to @ixkael and @tms-epcc on 20/DEC/23

**Comment by tms-epcc** [comment]
08/FEB/24
- following feedback from IPC team  to @tms-epcc, @damonge updated the workplan and resubmitted.
